# pandas의 1차원 자료형 - Series
- 1차원적인 데이터 형식
- 파이썬의 딕셔너리와 유사함

In [1]:
import pandas as pd

- Dictionary를 Series로

In [2]:
a = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50}

In [3]:
a

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [4]:
type(a)

dict

In [5]:
b = pd.Series(a)  # 파이썬 딕셔너리 타입을 판다스의 Series 데이터 구조로

In [6]:
b  # Series는 1차원적 구조를 갖는다.

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [7]:
type(b)

pandas.core.series.Series

In [8]:
b.shape  # 1차원, 값 5개

(5,)

- numpy array를 Series로 

In [9]:
import numpy as np

In [10]:
aa = np.arange(3, 10)

In [11]:
aa

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
bb = pd.Series(aa)  # numpy의 array 타입을 Series로 만들 수도 있다.

In [13]:
bb  # 딕셔너리와 달리 인덱스는 0부터 순차적으로 붙는다.

0    3
1    4
2    5
3    6
4    7
5    8
6    9
dtype: int32

In [14]:
type(bb)

pandas.core.series.Series

In [15]:
bb.shape

(7,)

- index

In [16]:
a  # 딕셔너리 접근

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

In [17]:
a.keys()

dict_keys(['a', 'b', 'c', 'd', 'e'])

In [18]:
a.values()

dict_values([10, 20, 30, 40, 50])

In [19]:
b

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
b.index  # 딕셔너리의 key에 해당

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
b.values  # 딕셔너리의 value에 해당

array([10, 20, 30, 40, 50], dtype=int64)

- list를 Series로

In [22]:
c = [10, 20, 30, 40, 50]  # list를 Series로 변경

In [23]:
d = pd.Series(c)

In [24]:
d

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [25]:
type(d)

pandas.core.series.Series

In [26]:
d.shape

(5,)

In [27]:
d.index  # 0부터 5 미만까지 1씩 커지는 range 형태

RangeIndex(start=0, stop=5, step=1)

In [28]:
d.values

array([10, 20, 30, 40, 50], dtype=int64)

- 딕셔너리 없이 인덱스 이름 넣기

In [29]:
e = ['a', 'b', 'c', 'd', 'e']  # 인덱스

In [30]:
f = [10, 20, 30, 40, 50]  # 값

In [31]:
g = pd.Series(f, index = e)

In [32]:
g

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [33]:
g['a']  # 인덱스 a의 값

10

In [34]:
g[0]  # 위치 값으로 접근

10

In [35]:
g['a':'d']  # d가 포함된다.

a    10
b    20
c    30
d    40
dtype: int64

In [36]:
g[0:4]  # 끝(4)이 포함되지 않는다.

a    10
b    20
c    30
d    40
dtype: int64