# numpy의 기본 연산과 조건 처리 1
- 사칙 연산
- 스칼라곱, 행렬곱

In [1]:
import numpy as np

In [2]:
a = np.arange(5, 45, 5).reshape(2, 4)

In [4]:
b = np.arange(20, 36, 2).reshape(2, 4)

In [5]:
a

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [6]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

- 스칼라곱

In [7]:
a + b  # 행과 열의 크기가 같을 때 가능

array([[25, 32, 39, 46],
       [53, 60, 67, 74]])

In [8]:
a - b

array([[-15, -12,  -9,  -6],
       [ -3,   0,   3,   6]])

In [9]:
a * b 

# 행렬곱은 앞 행렬의 열의 개수와 뒤 행렬의 행의 개수가 같을 때 가능
# numpy에서 제공된느 곱연산은 단순히 동일한 위치의 값끼리 곱해 주는 연산

array([[ 100,  220,  360,  520],
       [ 700,  900, 1120, 1360]])

In [10]:
a / b

array([[0.25      , 0.45454545, 0.625     , 0.76923077],
       [0.89285714, 1.        , 1.09375   , 1.17647059]])

In [11]:
a // b  # 몫 구하기 (정수 부분)

array([[0, 0, 0, 0],
       [0, 1, 1, 1]], dtype=int32)

In [12]:
a % b  # 나머지 구하기

array([[ 5, 10, 15, 20],
       [25,  0,  3,  6]], dtype=int32)

In [13]:
a * 10  # a 값들을 모두 10씩 곱해 주기

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

In [14]:
a  # a는 그대로 있다.

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [15]:
c = a * 10  # c라는 새로운 데이터 구조에 넣어 주면 된다.

In [16]:
c

array([[ 50, 100, 150, 200],
       [250, 300, 350, 400]])

- 행렬곱

In [17]:
b

array([[20, 22, 24, 26],
       [28, 30, 32, 34]])

In [18]:
bb = b.reshape(4, 2)

In [19]:
bb 

# a, c와의 곱이 가능해진다. (a, c는 2x4이므로)
# 행렬곱은 앞 행렬의 열의 개수와 뒤 행렬의 행의 개수가 같을 때 가능

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34]])

In [20]:
a @ bb  # 행렬곱 기호  # 2x4와 4x2이므로 2x2 행렬 도출

array([[1400, 1500],
       [3480, 3740]])

# numpy의 기본 연산과 조건 처리 2
- numpy의 조건 처리

In [21]:
a = np.arange(1, 15)

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
a > 10  # 비교 연산

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [24]:
a == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False])

In [25]:
a[a > 5]  # 5보다 큰 원소만 출력

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
a  # 값 자체가 바뀌진 않는다.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
a[a < 5] = 5  # 5보다 작은 a의 값은 전부 5 할당

In [28]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a[a > 10] = 10

In [30]:
a

array([ 5,  5,  5,  5,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])