# numpy의 1차원 자료형 1

In [2]:
import numpy as np

In [4]:
a = [10, 20, 30, 40, 50]

In [5]:
a

[10, 20, 30, 40, 50]

In [6]:
type(a)

list

In [7]:
b = np.array(a)  # list를 array 형식으로 가져온다.

In [8]:
b

array([10, 20, 30, 40, 50])

In [9]:
print(b)  # print로 출력하면 array 부분이 보이지 않는다.

[10 20 30 40 50]


In [10]:
b.shape  # 데이터 구조가 어떤 형태인지 보기 위해 사용  # 1차원, 5개

(5,)

In [11]:
c = np.array([5, 4, 3, 2, 1])  # 한번에 작성해도 된다.

In [12]:
c

array([5, 4, 3, 2, 1])

## numpy 연산

In [13]:
b + c  # 동일한 위치에 있는 값들끼리 덧셈 연산

array([15, 24, 33, 42, 51])

In [14]:
b + 5  # b의 5개 원소 각각에 대해 5를 더함

array([15, 25, 35, 45, 55])

In [15]:
a + 5  # 리스트는 이러한 연산이 불가하다.

TypeError: can only concatenate list (not "int") to list

In [16]:
a + [5, 4, 3, 2, 1]  # 파이썬 리스트는 그냥 쭉 나열하는 형태로 합한다.

[10, 20, 30, 40, 50, 5, 4, 3, 2, 1]

# numpy의 1차원 자료형 2

- 자주 사용하는 numpy 기본 함수

In [17]:
np.sum(b)  # 합계

150

In [18]:
np.mean(b)  # 평균

30.0

In [19]:
np.max(b)  # 최댓값

50

In [20]:
np.min(b)  # 최솟값

10

In [21]:
c = b / 3  # b의 모든 값을 3으로 나눈 구조를 c에 저장

In [22]:
c  # b도 array 형태였으므로 array로 저장된다.

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667])

In [23]:
np.round(c, 1)  # c라는 array를 소수점 첫 번째 자리까지 반올림

array([ 3.3,  6.7, 10. , 13.3, 16.7])

In [24]:
np.round(c, 3)

array([ 3.333,  6.667, 10.   , 13.333, 16.667])

In [25]:
np.round(c, 0)  # 그래도 .은 보인다.

array([ 3.,  7., 10., 13., 17.])

- numpy 데이터 구조의 특정 값에 접근 : index

In [26]:
b[0]  # zero-base이므로 0이 첫 번째 값

10

In [27]:
b[-1]  # 끝에서 첫 번째

50

In [28]:
b[1:3]  # 범위 인덱스  # 우리 기준 2번째, 3번째 값 가져오기

array([20, 30])

In [29]:
b[2:]  # 우리 기준 3번째부터 쭉

array([30, 40, 50])

In [30]:
np.sum(b[2:])  # 30 + 40 + 50

120

In [31]:
np.mean(b[2:])  # 120 / 3

40.0

In [32]:
b[1] = 200  # 특정 값 바꾸기

In [33]:
b

array([ 10, 200,  30,  40,  50])

- arange

In [34]:
d = np.arange(5)

In [35]:
d  # 파이썬 range 함수와 비슷

array([0, 1, 2, 3, 4])

In [36]:
e = np.arange(3, 8)  # 3부터 8 미만

In [37]:
e

array([3, 4, 5, 6, 7])

In [38]:
f = np.arange(3, 8, 2)  # 2씩 건너뛴다.

In [39]:
f

array([3, 5, 7])

- zeros

In [40]:
g = np.zeros(5)  # 0 벡터를 만들어 준다.

In [41]:
g

array([0., 0., 0., 0., 0.])

- ones

In [42]:
h = np.ones(5)

In [43]:
h

array([1., 1., 1., 1., 1.])

- copy

In [44]:
b

array([ 10, 200,  30,  40,  50])

In [45]:
bb = b

In [46]:
bb

array([ 10, 200,  30,  40,  50])

In [47]:
bb[0] = 100

In [48]:
bb

array([100, 200,  30,  40,  50])

In [49]:
b  # bb[0]만 바꿨는데 b[0]도 100으로 바뀌었다.

array([100, 200,  30,  40,  50])

In [50]:
bb = b.copy()

In [51]:
b[2] = 300

In [52]:
b

array([100, 200, 300,  40,  50])

In [53]:
bb  # copy로 값을 넘겼으므로 b 변경이 bb에 반영 안 된다.

array([100, 200,  30,  40,  50])

In [54]:
b == bb

array([ True,  True, False,  True,  True])