# numpy의 2차원 자료형

- 2차원적인 데이터 형식
- 행렬 연산이 가능함

In [1]:
import numpy as np

In [2]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [3]:
a  # 2차원 array

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
a.shape  # 2행 4열

(2, 4)

In [5]:
b, c = a.shape  # 행이나 열의 값이 별도로 필요할 때

In [6]:
b

2

In [7]:
c

4

- index

In [8]:
a[0, 0]  # 1행 1열 값

10

In [9]:
a[-1, -1]  # 마지막 행, 마지막 열 값

80

In [10]:
a[1, 1:]  # 2행 2열부터 끝까지

array([60, 70, 80])

In [11]:
a[0, 1] = 2  # 값 바꾸기

In [12]:
a

array([[10,  2, 30, 40],
       [50, 60, 70, 80]])

In [13]:
b = np.zeros((2, 4))  # 2x4 행렬 형태로 0 행렬

In [14]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
c = np.ones((3, 5))  # 3x5 행렬

In [16]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- reshape

In [17]:
c = np.arange(8)

In [18]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
c.reshape(2, 4)  # 차원 변경

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
c  # reshape은 비파괴적

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
c = c.reshape(2, 4)

In [22]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
c = c.reshape(4, 2)  # 4행 2열로 변경

In [24]:
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
c.sum()  # 전체 원소 합

28

In [26]:
d = c.copy()  # 값 복사

In [27]:
d[0, 0] = 10

In [28]:
d

array([[10,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [29]:
c  # 원래의 값은 변화 없음

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [30]:
c == d  # 0,0만 달라졌다.

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [31]:
e = np.arange(49).reshape(7, 7)  # arange를 바로 reshape 가능

In [32]:
e  # 0~48까지를 7행 7열로

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [33]:
e[:, 1:3]  # 행은 모두, 열은 2~3열만

array([[ 1,  2],
       [ 8,  9],
       [15, 16],
       [22, 23],
       [29, 30],
       [36, 37],
       [43, 44]])

In [34]:
e[3:, :4]  # 4행 이후, 3열까지

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [35]:
e[3:, :4].sum()  # 윗부분의 합계

528

In [36]:
f = e[3:, :4].copy() # 원하는 부분만 추려서 데이터 구조 가져오기

In [37]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [38]:
e[4, 0] = 100

In [39]:
e  # e 일부를 바꿔도 f는 영향이 없다.

array([[  0,   1,   2,   3,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12,  13],
       [ 14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27],
       [100,  29,  30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39,  40,  41],
       [ 42,  43,  44,  45,  46,  47,  48]])

In [40]:
f

array([[21, 22, 23, 24],
       [28, 29, 30, 31],
       [35, 36, 37, 38],
       [42, 43, 44, 45]])

In [41]:
f.sum()

528